const List<String> clubLevels = [
  "Kenyan Premier League",
  "Kenyan NSL",
  "Kenyan Division One",
  "Kenyan Division Two",
  "FKF Regional League",
  "Kenyan County League",
  "Kenyan Zonal League",
  "Ugandan Premier League",
  "Ligi Kuu Tanzania",
  "Ethiopian Premier League",
  "CECAFA Championship",
  "Community League",
  "Village League",
  "Village Soccer",
  "Primary School Soccer",
  "High School Soccer",

  // === REST OF AFRICA ===
  "CAF Champions League",
  "CAF Confederation Cup",
  "South African Premier  League ",
  "Egyptian Premier League",
  "Moroccan Botola Pro",
  "Nigerian Professional Football League",
  "Ghana Premier League",
  "Algerian Ligue Professionnelle 1",
  "Tunisian Ligue Professionnelle 1",
  "Angolan Girabola",
  "Ivorian Ligue 1",
  "African National First Division",
  "African Regional League",
  "African Provincial League",
  "African Women's League",

  // === OUTSIDE AFRICA - MAJOR LEAGUES & COMPETITIONS ===
  "English Premier League",
  "UEFA Champions League",
  "UEFA Europa League",
  "UEFA Conference League",
  "La Liga (Spain)",
  "Serie A (Italy)",
  "Bundesliga (Germany)",
  "Ligue 1 (France)",
  "Primeira Liga (Portugal)",
  "Eredivisie (Netherlands)",
  "Scottish Premiership",
  "Turkish Süper Lig",
  "Saudi Pro League",
  "Brazilian Série A",
  "Argentine Primera División",
  "Major League Soccer)",
  "A-League (Australia)",
  "J1 League (Japan)",
  "K League 1 (South Korea)",
  "Chinese Super League",

  // === LOWER TIERS & GENERAL ===
  "English Championship League One",
  "English Championship League Two",
  "Other European Top Division",
  "Other National Top Division",
  "National Second/Third Division",
  "Semi-Professional League",
  "Semi Amateur League",
  "Sunday League / Recreational",
  "Youth Academy / Reserve Team",
  "Women's Top Division (Global)",
];
